version: 2
jobs:
  lint:
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - run: sudo apt-get install shellcheck
      - run: ./bin/lint.sh
  build:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run: ./bin/build.sh
  test:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run: ./bin/test.sh
  publish:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run: ./bin/publish.sh
  deploy:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - run: sudo pip install awsebcli
      - checkout
      - run: ./bin/deploy.sh
  destroy:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - run: sudo pip install awsebcli
      - checkout
      - run: ./bin/destroy.sh
workflows:
  version: 2
  master:
    jobs:
      - build
      - test
      - publish
      - deploy
      - approve-destroy:
          type: approval
          requires:
            - deploy
      - destroy:
          requires:
            - approve-destroy
