version: 2
jobs:
  build_test:
    machine: true
    steps:
      - checkout
      - run: 
          name: build
          command: ./scripts/1-docker-build.sh
      - run: 
          name: test
          command: ./scripts/2-docker-test.sh
  build_test_tag_prod:
    machine: true
    steps:
      - checkout
      - run: 
          name: build
          command: ./scripts/1-docker-build.sh $CIRCLE_BRANCH-$CIRCLE_BUILD_NUM
      - run: 
          name: test
          command: command: ./scripts/2-docker-test.sh $CIRCLE_BRANCH-$CIRCLE_BUILD_NUM
      - run: 
          name: DockerHub tag and push
          command: ./scripts/docker-tag-and-push production-go-api $CIRCLE_BRANCH-$CIRCLE_BUILD_NUM
  deploy_prod:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - run:
          name: Install awsebcli
          command: sudo pip install awsebcli
      - checkout
      - run:
          name: Deploy
          command: ./scripts/deploy.sh production-go-api
  teardown_prod:
    machine: true
    steps: 
      - run
        - name: Tear environment now
        - command: ./scripts/teardown.sh production-go-api 
            
  
workflows:
  version: 2
  build-deploy:
    jobs:
      - build_test
          filters:
            branches: 
              ignore: master
      - build_test_tag_prod
          filters:
            branches:
              only: master
      - hold_deploy_prod:
          type: approval 
          requires: 
            - build_test_tag_prod
          filters:
            branches:
              only: master
      - hold_teardown_prod:
          type: approval
          requires:
            deploy_prod
          filters:
            branches:
              only: master
      - deploy_prod:
          requires:
            - hold_deploy_prod
          filters:
            branches:
              only: master