version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t chips5k/go-api:$CIRCLE_BRANCH .
      - run: docker run --entrypoint go chips5k/go-api:$CIRCLE_BRANCH  test
      - run: echo "$DOCKER_PASS" | docker login --username chips5k --password-stdin
      - run: docker push chips5k/go-api:$CIRCLE_BRANCH